version: '3.8'

services:
  webapp:
    build: .
    image: mi-app-flask:latest
    ports:
      - "8080:5000" # Mapea el puerto 8080 local al 5000 del contenedor
    volumes:
      - ./app:/app # Permite ver cambios de código en tiempo real (desarrollo)
    environment:
      - FLASK_ENV=development
      - FLASK_HOST=0.0.0.0  # Permitido en desarrollo local dentro de la red de Docker
      - FLASK_DEBUG=True     # Permitido en desarrollo local